var SUPABASE_URL = 'https://rnnrimzrypayvnmznpin.supabase.co';
var SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJubnJpbXpyeXBheXZubXpucGluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ1MTQzNzIsImV4cCI6MjA5MDA5MDM3Mn0.08KrHBEVgFHXZtxXSdJ5-Z0DWuxvHdsSkTzXtUztduo';
