-- Phase 3A: add fighters.nickname + populate high/medium-confidence nicknames
-- Source: reports/fighter_nickname_candidates.csv (high/medium only, 137 fighters)
-- NOTE: source_url / confidence / note are intentionally NOT stored in DB (kept in reports CSV only).
-- Match key = name_en (exact). fighters.name_en has zero duplicates table-wide (verified), so each
-- VALUES row matches at most one fighter. ID_MISMATCH rows (id slug != name) are resolved by name_en,
-- never by id. no_known_nickname (41) and needs_manual_check (2) rows are left NULL on purpose.

ALTER TABLE public.fighters ADD COLUMN IF NOT EXISTS nickname text;

ALTER TABLE public.fighters DROP CONSTRAINT IF EXISTS fighters_nickname_len_chk;
ALTER TABLE public.fighters
  ADD CONSTRAINT fighters_nickname_len_chk
  CHECK (nickname IS NULL OR char_length(btrim(nickname)) BETWEEN 1 AND 80);

UPDATE public.fighters AS f
SET nickname = v.nickname
FROM (VALUES
  ('Petr Yan','No Mercy'),
  ('Merab Dvalishvili','The Machine'),
  ('Sean O''Malley','Suga'),
  ('Cory Sandhagen','The Sandman'),
  ('Song Yadong','The Kung Fu Kid'),
  ('Deiveson Figueiredo','Daico'),
  ('David Martinez','Black Spartan'),
  ('Marlon Vera','Chito'),
  ('Vinicius Oliveira','LokDog'),
  ('Raul Rosas Jr.','El Niño Problema'),
  ('Montel Jackson','Quik'),
  ('Farid Basharat','Ferocious'),
  ('Joshua Van','The Fearless'),
  ('Alexandre Pantoja','The Cannibal'),
  ('Manel Kape','Starboy'),
  ('Brandon Royval','Raw Dawg'),
  ('Kyoji Horiguchi','Karate Kid'),
  ('Amir Albazi','The Prince'),
  ('Asu Almabayev','Zulfikar'),
  ('Brandon Moreno','The Assassin Baby'),
  ('Steve Erceg','Astro Boy'),
  ('Charles Johnson','InnerG'),
  ('Bruno Silva','Bulldog'),
  ('Alexander Volkanovski','The Great'),
  ('Lerone Murphy','The Miracle'),
  ('Aljamain Sterling','Funk Master'),
  ('Yair Rodriguez','El Pantera'),
  ('Jean Silva','Lord'),
  ('Arnold Allen','Almighty'),
  ('Youssef Zalal','The Moroccan Devil'),
  ('Steve Garcia','Mean Machine'),
  ('Kevin Vallejos','El Chino'),
  ('Brian Ortega','T-City'),
  ('Melquizael Costa','The Dalmatian'),
  ('David Onama','Silent Assassin'),
  ('Ciryl Gane','Bon Gamin'),
  ('Alex Pereira','Poatan'),
  ('Alexander Volkov','Drago'),
  ('Waldo Cortes Acosta','Salsa Boy'),
  ('Josh Hokit','The Incredible Hok'),
  ('Serghei Spivac','Polar Bear'),
  ('Curtis Blaydes','Razor'),
  ('Derrick Lewis','The Black Beast'),
  ('Ante Delija','Walking Trouble'),
  ('Marcin Tybura','Tybur'),
  ('Valter Walker','The Clean Monster'),
  ('Brando Peričić','The Balkan Bear'),
  ('Tallison Teixeira','Xicao'),
  ('Carlos Ulberg','Black Jag'),
  ('Jiří Procházka','Denisa'),
  ('Khalil Rountree Jr.','The War Horse'),
  ('Jamahal Hill','Sweet Dreams'),
  ('Paulo Costa','Borrachinha'),
  ('Azamat Murzakanov','The Professional'),
  ('Volkan Oezdemir','No Time'),
  ('Robert Whittaker','The Reaper'),
  ('Bogdan Guskov','Czarevitch'),
  ('Dominick Reyes','The Devastator'),
  ('Aleksandar Rakić','Rocket'),
  ('Nikita Krylov','The Miner'),
  ('Alonzo Menifield','Atomic'),
  ('Ilia Topuria','El Matador'),
  ('Justin Gaethje','The Highlight'),
  ('Arman Tsarukyan','Akhalkalakets'),
  ('Charles Oliveira','do Bronx'),
  ('Max Holloway','Blessed'),
  ('Benoît Saint Denis','God of War'),
  ('Paddy Pimblett','The Baddy'),
  ('Mateusz Gamrot','Gamer'),
  ('Dan Hooker','The Hangman'),
  ('Renato Moicano','Money Moicano'),
  ('Mauricio Ruffy','One Shot'),
  ('Rafael Fiziev','Ataman'),
  ('Michael Chandler','Iron'),
  ('Farès Ziam','Smile Killer'),
  ('Sean Strickland','Tarzan'),
  ('Khamzat Chimaev','Borz'),
  ('Dricus Du Plessis','Stillknocks'),
  ('Nassourdine Imavov','The Sniper'),
  ('Caio Borralho','The Natural'),
  ('Brendan Allen','All In'),
  ('Joe Pyfer','Bodybagz'),
  ('Anthony Hernandez','Fluffy'),
  ('Reinier de Ridder','The Dutch Knight'),
  ('Israel Adesanya','The Last Stylebender'),
  ('Jared Cannonier','Tha Killa Gorilla'),
  ('Gregory Rodrigues','Robocop'),
  ('Christian Leroy Duncan','CLD'),
  ('Roman Dolidze','The Caucasian'),
  ('Julianna Peña','The Venezuelan Vixen'),
  ('Raquel Pennington','Rocky'),
  ('Joselyne Edwards','La Pantera'),
  ('Norma Dumont','The Immortal'),
  ('Ailin Perez','Fiona'),
  ('Ketlen Vieira','Fenômeno'),
  ('Yana Santos','Foxy'),
  ('Jacqueline Cavalcanti','The Nightmare'),
  ('Michelle Montague','The Wild One'),
  ('Nora Cornolle','Wonder'),
  ('Bia Mesquita','The Lady GOAT'),
  ('Miesha Tate','Cupcake'),
  ('Valentina Shevchenko','Bullet'),
  ('Zhang Weili','Magnum'),
  ('Manon Fiorot','The Beast'),
  ('Erin Blanchfield','Cold Blooded'),
  ('Rose Namajunas','Thug'),
  ('Maycee Barber','The Future'),
  ('Miranda Maverick','Fear The'),
  ('Karine Silva','Killer'),
  ('Casey O''Neill','King'),
  ('Wang Cong','The Joker'),
  ('Eduarda Moura','Ronda'),
  ('Gabriella Fernandes','Gabi'),
  ('Virna Jandiroba','Carcará'),
  ('Yan Xiaonan','Fury'),
  ('Gillian Robertson','The Savage'),
  ('Loopy Godinez','Loopy'),
  ('Amanda Lemos','Amandinha'),
  ('Tabatha Ricci','Baby Shark'),
  ('Jéssica Andrade','Bate Estaca'),
  ('Fatima Kline','The Archangel'),
  ('Denise Gomes','Dee'),
  ('Alexia Thainara','Burguesinha'),
  ('Angela Hill','Overkill'),
  ('Ian Machado Garry','The Future'),
  ('Carlos Prates','The Nightmare'),
  ('Jack Della Maddalena','JDM'),
  ('Belal Muhammad','Remember the Name'),
  ('Leon Edwards','Rocky'),
  ('Kamaru Usman','The Nigerian Nightmare'),
  ('Joaquin Buckley','New Mansa'),
  ('Yaroslav Amosov','Dynamo'),
  ('Gabriel Bonfim','Marretinha'),
  ('Uroš Medić','The Doctor'),
  ('Michael Venom Page','Venom'),
  ('Colby Covington','Chaos'),
  ('Daniel Rodriguez','D-Rod')
) AS v(name_en, nickname)
WHERE f.name_en = v.name_en;
